FROM golang:1.23 AS builder

ARG CGO_ENABLED=0
ARG APP_ENV
ARG SERVER_ADDRESS
ARG PORT
ARG CONTEXT_TIMEOUT
ARG DB_TYPE
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASS
ARG DB_NAME
ARG ACCESS_TOKEN_EXPIRY_HOUR
ARG REFRESH_TOKEN_EXPIRY_HOUR
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o abare-server cmd/main.go

FROM scratch AS runner
COPY --from=builder /app/abare-server /abare-server

ENV APP_ENV=${APP_ENV}
ENV SERVER_ADDRESS=${SERVER_ADDRESS}
ENV PORT=${PORT}
ENV CONTEXT_TIMEOUT=${CONTEXT_TIMEOUT}
ENV DB_TYPE=${DB_TYPE}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASS=${DB_PASS}
ENV DB_NAME=${DB_NAME}
ENV ACCESS_TOKEN_EXPIRY_HOUR=${ACCESS_TOKEN_EXPIRY_HOUR}
ENV REFRESH_TOKEN_EXPIRY_HOUR=${REFRESH_TOKEN_EXPIRY_HOUR}
ENV ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
ENV REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

# print APP_ENV to check if it is set and await for 10 seconds
RUN echo $APP_ENV && sleep 5


CMD ["/abare-server"]