name: Audit

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...

  #deploy:
  #  needs: audit
  #  # only if branch is main
  #  if: github.ref == 'refs/heads/main'
  #  runs-on: ubuntu-20.04
  #  steps:
  #  - uses: actions/checkout@v2
  #
  #  - name: Trigger deploy
  #    run: curl -X POST https://inovadata.tech/api/deploy/cqHRfzTUZjJ5ZgVOJ79mk